#Updated by CMS UI
#Sat Mar 21 16:55:59 PKT 2026
ai.sensitivity=75
app.auto.backup=true
app.default.precinct=Central
app.evidence.storage.path=./data/evidence
app.model.path=./models
app.name=CMS v2.0
app.password.lockout.attempts=5
app.password.lockout.minutes=30
app.session.timeout.minutes=20
app.time.format=24H
app.timezone=UTC
db.host=localhost
db.name=cms_db
db.password=password
db.port=3306
db.ssl=false
db.user=root
