package com.cms.model.enums;

public enum Role {
    ADMINISTRATOR,
    SUPERVISOR,
    OFFICER,
    DETECTIVE,
    ANALYST,
    RECORDS_CLERK,
    PROSECUTOR,
    LEGAL_OFFICER,
    PUBLIC_RELATIONS,
    FIELD_AGENT,
    INTERNAL_AFFAIRS,
    AUDITOR,
    MANAGEMENT
}
